---
title: "Practical: Network meta-analysis with hazard ratio summaries alongside count data"
output: 
  pdf_document
format:
  pdf
links: 
  - name: ""
    icon: slideshare
    icon_pack: fab
    # url: /slides/07_NMA/index.html
  - name: "PDF version"
    # url: practical6.pdf
    icon: file-pdf
    icon_pack: fas
---


## 1. Introduction

Data and BUGS code from Woods (2010).
They are saved in `part 2/practical/hr_counts_input_data.RData` and created at
the top of the analysis `R` script.
The data include the following variables:

-   `Lstudy`: Hazard study ID

-   `Ltx`: Hazard study treatment index

-   `Lbase`: Hazard study base treatment

-   `Lmean`: Mean hazard ratio

-   `Lse`: Hazard ratio standard error

-   `multi`: Multiple arm study

-   `Bstudy`: Binary data study ID

-   `Btx`: Binary data treatment index

-   `Bbase`: Binary data base treatment 

-   `Br`: Binary data number of events

-   `Bn`: Binary data total number of individuals

-   `LnObs`: Hazard data number of observations

-   `BnObs`: Binary data number of observations

-   `nTx`: Total number of treatments

-   `nStudies`: Total number of studies

The `R` script [`Woods_script.R`](part 2/practical/Woods_script.R) guides you through the
analysis.

## 2. BUGS code

Look at the BUGS code in the file [`Woods_BUGS_code_FE.txt`](part 2/practical/Woods_BUGS_code_FE.txt).
This is the fixed effects version of the model.

## 3. Running the model

- Run the model using the `bugs()` command and inspect the output.

- What is the conclusion?


